version: '3.5'

services: # Here we define our service(s)
    service: # The name of the service
      build: . # Location of our Dockerfile
      volumes: # Volume binding
        - '.:/usr/src/app'
        - '/usr/src/app/node_modules'
      ports:
        - '4200:4200' # Port mapping
      command: >
        bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"
